rust: fix inconsistent result ordering (#279)
* [rust] add intermittently failing test for misordered search results

This fails approximately half the time:

    failures:

    ---- packed_r_tree::tree_19items_roundtrip_stream_search stdout ----
    thread 'packed_r_tree::tree_19items_roundtrip_stream_search' panicked at 'assertion failed: `(left == right)`
      left: `[16, 13, 14, 15]`,
     right: `[13, 14, 15, 16]`', src/packed_r_tree.rs:781:5
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

* [rust] fix misordered results for `search`

HashMap doesn't guarantee ordering.

* [rust] simpler/faster to use a Queue

Since we traverse the tree in order, we can more simply/quickly use a
queue rather than a sorting data structure.